  project:
    type: website
    output-dir: docs

  website:
    title: "blog-template"
    navbar:
      right:
        - about.qmd
        - icon: github
          href: https://github.com/mozuqi25/
  format:
    html:
      theme: cosmo
      css: styles.css
      mainfont: system-ui
      headingfont: Verdana
