  project:
    type: website
    output-dir: docs

  website:
    title: "The Uncertain Analyst's Blog"
    favicon: "images/favicon.png"
    navbar:
      right:
        - text: "About"
          file: about.qmd
        - icon: github
          href: https://github.com/mozuqi25/

  page-footer:
    background: dark
    left: |
      **M. Zulkifli Falaqi**<br>
      © 2025
    right:
      - icon: github
        href: https://github.com/mozuqi25
      - icon: envelope
        href: mailto:mfal0012@student.monash.edu
      - icon: twitter
        href: https://www.x.com/mozuqi/
      - text: "Melbourne, VIC, Australia"

  format:
    html:
      theme: cosmo
      css: styles.css
      mainfont: system-ui
      headingfont: Verdana
